GET http://localhost:5000/api/v1/admin/users
# Content-Type: application/json

# {
#     "name": "Syed Sheharyar",
#     "email": "syedsheharyar146@gmail.com",
#     "password": "syedsheharyar146"
# }
